### PR TITLE
Feature/add device support

### PR DESCRIPTION
**Pull request by ycliuhw**
upgraded charm.v3 to add device support

### CODE REVIEW

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/jujusvg/113/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/jujusvg/114/

**Review by wallyworld — APPROVED** [review]

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/jujusvg/115/

**Comment by ycliuhw** [comment]
$$merge$$

**Comment by ycliuhw** [comment]
[add ability of parsing device constraints to bundlechanges repo](https://trello.com/c/uCvdH2xt/298-add-ability-of-parsing-device-constraints-to-bundlechanges-repo)

**Pull request merged**
