### PR TITLE
Scale icons from 120px to 96px

### PR DESCRIPTION
**Pull request by makyo**
This finishes the bundle vis scaling, resizing the service blocks from 120px to 96px, which was the size of the service blocks in the GUI (where the bundles are built)

### CODE REVIEW

**Comment by makyo** [comment]
QA:

* Pull this branch down, and CD to that dir
* `go build ./...`
* `go run examples/generatesvg.go examples/openstack.yaml >../../../../bundle.svg`
* Open `file:///$GOHOME/bundle.svg` in chrome, ensure that the service blocks are smaller and the relation lines still meet up with the cardinal points

**Comment by mhilton** [comment]
:+1: LGTM QA looks OK too. I built a charmstore with this version of jujusvg. and created a diagram using http://localhost:8080/v4/bundle/rails-example-scalable-6/diagram.svg

**Comment by hatched** [comment]
:+1: QA OK!

**Comment by makyo** [comment]
Thanks for the reviews!

**Pull request merged**
