### PR TITLE
Add titles to relations and services

### PR DESCRIPTION
**Pull request by makyo**

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/jujusvg/60/
Test PASSed.

**Comment by makyo** [comment]
# QA

Run `go run examples/generatesvg.go examples/mediawiki-scalable.yaml   > bundle.svg` and open the SVG in the browser.  Hovering over both services and relations should show their titles.

**Comment by makyo** [comment]
Fixes #35

**Comment by bac** [comment]
:+1:

**Comment by bac** [comment]
QA- :sushi:

**Comment by makyo** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/jujusvg-merge

**Pull request merged**
