### PR TITLE
Update deps and switch to new bundle Verify signature.

### PR DESCRIPTION
**Pull request by frankban**

### CODE REVIEW

**Comment by mhilton** [comment]
:+1:

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/jujusvg/52/
Test PASSed.

**Comment by urosj** [comment]
:+1:

**Comment by urosj** [comment]
:shipit:

**Comment by frankban** [comment]
Thanks for the reviews!
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/jujusvg-merge

**Pull request merged**
