### PR TITLE
version 2

### PR DESCRIPTION
**Pull request by mhilton**

### CODE REVIEW

**Comment by urosj** [comment]
👍

**Comment by rogpeppe** [comment]
LGTM, thanks

**Comment by mhilton** [comment]
:shipit:

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/jujusvg/77/
Test FAILed.

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/jujusvg-merge

**Comment by jujugui** [comment]
Build failed: Attempt to land pull request failed
        build url: http://ci.jujugui.org:8080/job/jujusvg-merge/25

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/jujusvg/80/
Test PASSed.

**Comment by mhilton** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/jujusvg-merge

**Pull request merged**
