### PR TITLE
Update to use gopkg.in/juju/jujusvg.v1

### PR DESCRIPTION
**Pull request by johnweldon**
Update to use gopkg.in

### CODE REVIEW

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/jujusvg/24/
Test FAILed.

**Comment by wallyworld** [comment]
Test output:

+ export GOPATH=/tmp/build/24
+ GOPATH=/tmp/build/24
+ trap 'rm -rf /tmp/build/24' 0
+ export PATH=/tmp/build/24/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
+ PATH=/tmp/build/24/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
+ mkdir -p /tmp/build/24/src/github.com/juju
+ cp -r . /tmp/build/24/src/github.com/juju/jujusvg
+ cd /tmp/build/24/src/github.com/juju/jujusvg
+ make deps
Makefile:38: *** Cannot deps; /tmp/build/24/src/github.com/juju/jujusvg is not on GOPATH.  Stop.
+ rm -rf /tmp/build/24
Build step 'Execute shell' marked build as failure
Test FAILed.

**Comment by johnweldon** [comment]
It seems that the CI job needs to know about switching to gopkg.in/juju/jujusvg.v1 for this branch?

**Comment by makyo** [comment]
@johnweldon I'll look into it on CI's side.

**Pull request closed without merging**
