### PR TITLE
govers gopkg.in/juju/charm.v6-unstable

### PR DESCRIPTION
**Pull request by rogpeppe**
It's the latest version and we can't update charmstore to use charm.v6 until this happens.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/jujusvg/19/
Test PASSed.

**Comment by makyo** [comment]
:+1: as trivial

**Comment by rogpeppe** [comment]
:shipit:

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/jujusvg/20/
Test PASSed.

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/jujusvg-merge

**Pull request merged**
