### PR TITLE
Use transforms for masks for firefox

### LINKED ISSUE #42: Clip-path problem in firefox
See CanonicalLtd/jujucharms.com#206

### PR DESCRIPTION
**Pull request by makyo**
fixes #42
fixes CanonicalLtd/jujucharms.com#206

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/jujusvg/58/
Test PASSed.

**Comment by makyo** [comment]
# QA

Run `go run examples/generatesvg.go examples/mediawiki-scalable.yaml  > bundle.svg` and open the result in Firefox.  Clip paths should be centered

**Comment by anthonydillon** [comment]
Code :ok: and QA :+1:

**Comment by makyo** [comment]
Landing as trivial :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/jujusvg-merge

**Pull request merged**
